spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8


# 忽略swagger java.lang.NumberFormatException: For input string: ""
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error